### ISSUE TITLE
add color clok & brightness  & clok scroll

### ISSUE THREAD

**Issue by ananyevgv** [andrewjswan/matrix-lamp#12]
add color clok & brightness:

 ```yaml
 - platform: esp32_rmt_led_strip
    pin: $pin_rmt
    num_leds: 1
    name: Color clock
    id: color_clock
    icon: mdi:clock-digital
    rgb_order: GRB
    chipset: WS2812
    rmt_channel: 0
    on_turn_on:
      - light.turn_off:
          id: neopixel_led
    on_turn_off:
      - lambda: |-
          id(neopixel_display)->get_light()->set_correction(1.0, 1.0, 1.0);
      - light.turn_on:
          id: neopixel_led
  

display:
    lambda: |-
      auto font_color = Color(id(color_clock).remote_values.get_red()*255,id(color_clock).remote_values.get_green()*255 ,id(color_clock).remote_values.get_blue()*255 );
      
      static int i = 0;
      i++;
      if ((i % 2) == 0) 
        it.print(WIDTH/2, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER, ":");
      it.strftime(WIDTH/4, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER, "%H", id(matrix_lamp_time).now());
      it.strftime(WIDTH/2+WIDTH/4, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER, "%M", id(matrix_lamp_time).now());
      
      auto clock_br = id(color_clock).remote_values.get_brightness();
      id(neopixel_display)->get_light()->set_correction(clock_br, clock_br, clock_br);
```
scroll

 ```yaml
    lambda: |-
      auto font_color = Color(id(color_clock).remote_values.get_red()*255,id(color_clock).remote_values.get_green()*255 ,id(color_clock).remote_values.get_blue()*255 );

      //
      static int i = 0;
      i++;
      if ( i <= 4)  {
        it.print(WIDTH/2, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER, ":");
      }
      else 
        if ( i == 8)
          i = 0;
      // 
      uint8_t HH = (id(matrix_lamp_time).now().hour);
      uint8_t HD = HH / 10;
      uint8_t h = HH % 10;
      static uint8_t HDk;
      static uint8_t hk;

      // 
      uint8_t MM = (id(matrix_lamp_time).now().minute);
      uint8_t MD = MM / 10;
      uint8_t m = MM % 10;
      static uint8_t MDk;
      static uint8_t mk;

      // Разбираем секунды
      //uint8_t SS = (id(matrix_lamp_time).now().second);
      //uint8_t SD = SS / 10;
      //uint8_t s = SS % 10;
      //static uint8_t SDk = 0;
      //static uint8_t sk = 0;

      // 
      if (h != hk)   {
        static int hi = 0;
        it.printf(WIDTH/4+WIDTH/8, hi-HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", h );
        it.printf(WIDTH/4+WIDTH/8, hi+HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", hk );
        hi++;
        if (hi == 8) {
          hi = 0;
          hk = h;
        }
      }  
      else
        it.printf(WIDTH/4+WIDTH/8, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", h );

      // 
      if ( HD != HDk )   {
        static int HDi = 0;
        it.printf(WIDTH/8, HDi-HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER, "%u", HD );
        it.printf(WIDTH/8, HDi+HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", HDk );
        HDi++;
        if (HDi == 8) {
          HDi = 0;
          HDk = HD;
        }
      }  
      else
        it.printf(WIDTH/8, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", HD );


      // 
      if (m != mk)   {
        static int mi = 0;
        it.printf(WIDTH/2+WIDTH/4+WIDTH/8,mi-HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", m );
        it.printf(WIDTH/2+WIDTH/4+WIDTH/8, mi+HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", mk );
        mi++;
        if (mi == 8) {
          mi = 0;
          mk = m;
        }
      }  
      else
        it.printf(WIDTH/2+WIDTH/4+WIDTH/8, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", m );

      // 
      if (MD != MDk)   {
        static int MDi = 0;
        it.printf(WIDTH/2+WIDTH/8, MDi-HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", MD );
        it.printf(WIDTH/2+WIDTH/8, MDi+HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", MDk );
        MDi++;
        if (MDi == 8) {
          MDi = 0;
          MDk = MD;
        }
      }  
      else
        it.printf(WIDTH/2+WIDTH/8, HEIGHT/2, id(px8_font), font_color, TextAlign::CENTER,"%u", MD );
      
      auto clock_br = id(color_clock).remote_values.get_brightness();
      id(neopixel_display)->get_light()->set_correction(clock_br, clock_br, clock_br);
 ```
